#pragma once
#define PLUG_NAME "MidiQueueProbe"
#define PLUG_MFR "IPlugTests"
#define PLUG_VERSION_HEX 0x00010000
#define PLUG_VERSION_STR "1.0.0"
#define PLUG_UNIQUE_ID 'Mq95'
#define PLUG_MFR_ID 'IpTs'
#define PLUG_URL_STR "https://github.com/pluginmaker-ai/iPlug2"
#define PLUG_EMAIL_STR ""
#define PLUG_COPYRIGHT_STR "iPlug2 test fixture"
#define PLUG_CLASS_NAME MidiQueueProbe
#define BUNDLE_NAME "MidiQueueProbe"
#define BUNDLE_MFR "IPlugTests"
#define BUNDLE_DOMAIN "org"
#define PLUG_CHANNEL_IO "0-2"
#define PLUG_LATENCY 0
#define PLUG_TYPE 1
#define PLUG_DOES_MIDI_IN 1
#define PLUG_DOES_MIDI_OUT 0
#define PLUG_DOES_MPE 0
#define PLUG_DOES_STATE_CHUNKS 0
#define PLUG_HAS_UI 0
#define PLUG_WIDTH 100
#define PLUG_HEIGHT 100
#define PLUG_FPS 0
#define PLUG_HOST_RESIZE 0
#define PLUG_SHARED_RESOURCES 0
#define AUV2_ENTRY MidiQueueProbe_Entry
#define AUV2_ENTRY_STR "MidiQueueProbe_Entry"
#define AUV2_FACTORY MidiQueueProbe_Factory
#define AUV2_VIEW_CLASS MidiQueueProbe_View
#define AUV2_VIEW_CLASS_STR "MidiQueueProbe_View"
#define VST3_SUBCATEGORY "Instrument|Synth"
